variable "tenant" {}
variable "name" {}
variable "environment" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "enable_aws_cicd" {}
variable "pipeline_name" {}
variable "connection_arn" {}
variable "repository" {}
variable "branch" {}
variable "detect_changes" {}
variable "buildspec" {}
variable "deployspec" {}
variable "vpc_enabled" {}
variable "privileged_mode" {}
variable "build_timeout" {}
variable "queued_timeout" {}
variable "compute_type" {}
variable "deployer_version" {}
variable "image" {}
variable "librepos" {}
